file_format: "1"
id: openwork36
name: openwork36
type: shield
url: https://github.com/jimmerricks/swoop
requires: [pro_micro]
features:
  - keys
  - pointer
siblings:
  - openwork36_left
  - openwork36_right
